# Generated by Django 5.1.4 on 2024-12-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('sender_address', models.CharField(max_length=255)),
                ('recipient_address', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, null=True)),
                ('nft_url', models.URLField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
